name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Export environment variables to .env.local
        env:
          VARS: ${{ secrets.VARS }}
        run: |
          echo "${{ secrets.VARS }}" > vars.env 
          while IFS= read -r line; do
            echo "VITE_${line}" >> .env.local
          done < vars.env
          cat .env.local

      - name: Build the project
        run: npm run build --if-present

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "dist/**"
          target: "/var/www/front"
